#!/bin/bash

menu() {
    clear
    dia=$(date +%d)
    mes=$(date +%B)
    ano=$(date +%Y)

    formatacao_data=$(printf "%-59s" "# Rio de Janeiro, $dia de $mes de $ano")

    echo "############################################################"
    echo "# IBMEC                                                    #"
    echo "# Sistemas Operacionais                 Semestre 1 de 2024 #"
    echo "# Código IBM8940                        Turma 8001         #"
    echo "# Professor: Luiz Fernando T. Farias                       #"
    echo "#----------------------------------------------------------#"
    echo "# Equipe Desenvolvedora:                                   #"
    echo "#   Aluno: João Pedro Martinez                             #"
    echo "#   Aluno: Phillipe Secondo                                #"
    echo "#----------------------------------------------------------#"
    echo "${formatacao_data}#"
    echo "# Hora do Sistema: $(date +%H) horas e $(date +%M) minutos                   #"
    echo "############################################################"
    echo ""
    echo "Menu de Escolhas:"
    echo "  1) Escolha 1"
    echo "  2) Escolha 2"
    echo "  3) Como adicionar mais armazenamento na MV"
    echo "  4) Montar Partição"
    echo "  5) Finalizar Programa"
    echo ""
    echo "Selecione uma opção:"
}

montar_particao() {
    echo "Digite o dispositivo/partição que deseja criar (ex: /dev/sdb):"
    read  dispositivo
    echo "Digite a partição a ser formatada (ex: /dev/sdb1):"
    read  particao
    echo "Digite o Sistema de Arquivo que deseja usar:"
    read  sistemaArq
    echo "Digite o diretório de montagem:"
    read  particao_criada

    if [ ! -e "$dispositivo" ]; then
        echo "Dispositivo não conectado"
        return 1
    fi
    
    echo -e "n\np\n\n\n\nw" | sudo fdisk "$dispositivo"
    
    sudo mkfs."$sistemaArq" "$particao"
    
    sudo mkdir "$particao_criada"
    
    sudo mount "$particao" "$particao_criada"
}

processar_opcao() {
    read -r opcao
    case $opcao in
        1) echo "Você selecionou a opção 1." ;;
        2) echo "Você selecionou a opção 2." ;;
        3) func_comunica_gpt ;;
        4) montar_particao ;;
        5) echo "Programa finalizado." ;;
        *) echo "Opção inválida. Por favor, escolha novamente." ;;
    esac
}

func_comunica_gpt() {
    firefox "https://chatgpt.com/?oai-dm=1&q=Como+adicionar+um+dispositivo+na+Maquina+Virtual+Virtual+Box+Oracle"
}

menu
processar_opcao
